### ISSUE TITLE
survey_drive.py: ModuleNotFoundError: No module named 'bagit'

### ISSUE THREAD

**Issue by genfhk** [NYPL/ami-tools#12]
MY-PAMI-061930:ami-tools genevievehavemeyerking$ python3 /Users/genevievehavemeyerking/ami-tools/bin/survey_drive.py -d /Volumes/NYPL_16650/ -o /Users/genevievehavemeyerking/Desktop/drop_folder 
**Traceback (most recent call last):
  File "/Users/genevievehavemeyerking/ami-tools/bin/survey_drive.py", line 4, in <module>
    import bagit
ModuleNotFoundError: No module named 'bagit'**

**Comment by nkrabben** [comment]
quick fix is pip3 install bagit

**Comment by genfhk** [comment]
fixed: line 4 - "**from ami_bag** import bagit"

**Comment by nkrabben** [comment]
that also works

**Comment by genfhk** [comment]
I have bagit already. Thanks tho

**Comment by nkrabben** [comment]
Do you have it for python3? It should auto-install with ami-tools, but if it didn't I have another bug to chase.

**Comment by genfhk** [comment]
I do, but I installed it before I installed ami-tools, so I can't say if it tried to reinstall it or not

**Comment by nkrabben** [comment]
Is bagit listed when you run `pip3 list`?

**Comment by nkrabben** [comment]
I was testing for it, but not requiring install. Doh!
https://github.com/NYPL/ami-tools/commit/e6ec8df694d5dde9f80a43f30e1b20c3e7eafaf2
