### ISSUE TITLE
better error messages for validate_ami_bags.py

### ISSUE THREAD

**Issue by genfhk** [NYPL/ami-tools#20]
Suggestions: 
1. for complex bags, instead of 'invalid', give 'warning' to differentiate from more critical errors. 
2. for 'ready' vs. 'not ready' for ingest, give percentage or fraction ("1450 of 1500 bags are ready for ingest")
2b. this tool is meant to evaluate 'ingestability' - so complex bags are flagged as 'not ready for ingest'. For QC, this makes it hard to pinpoint actual fixity/structure failures in the giant haystack of 'not ready for ingest' bags, as there are many complex bags. Can complex bags be their own category in the report (i.e. 'too complex for ingest')?

**Comment by nkrabben** [comment]
Addressed in 543715b5c7c0c568a117a1ab23d50912af962bea
Warnings report invalid ami bags, errors report invalid bagit bags
