### ISSUE TITLE
pamidb_to_json.py: prevent 0 measurements from getting killed by pandas

### ISSUE THREAD

**Issue by bturkus** [NYPL/ami-tools#28]
this is new one: when exporting a mer with a significant number of zeroes as a measurement (say, for example, phono preamp eqrolloff), the json created seems to have no measure value at all. Looks like this:

![screen shot 2018-04-11 at 5 12 34 pm](https://user-images.githubusercontent.com/8987230/38643579-9493871e-3dab-11e8-8a74-58dc39d01da5.png)

I believe this is a pandas thing (not Filemaker, though I'm not 100%).

**Comment by nkrabben** [comment]
Is this still an issue?

**Comment by bturkus** [comment]
I think it is but it rarely comes up

**Comment by bturkus** [comment]
closing for now will reopen or send new issue if this arises
