### ISSUE TITLE
validate_ami_bags: additional json test?

### ISSUE THREAD

**Issue by bturkus** [NYPL/ami-tools#43]
Interesting recent case: in-house audio project passes json validation and is considered "ready for ingest" by validate_ami_bags, but the actual information inside many of the the json files is incorrect (it was a rare situation in which we made a series of mistakes that resulted in correct json filenames but incorrect data within).

I know it's a little out of scope, but could we consider adding some sort of test that looks inside json files and matches on filenames or technical metadata?

**Comment by nkrabben** [comment]
Does it still pass if you use --metadata?

**Comment by bturkus** [comment]
no, it doesn't, and this is perfect. sorry i didn't realize it had this functionality with json (we should adjust the help description of the metadata flag to reflect this). thanks!
