### ISSUE TITLE
request: replace the word "error" for anything within non "ERROR" categories. 

### ISSUE THREAD

**Issue by genfhk** [NYPL/ami-tools#51]
i.e. 
replace ...

WARNING - **Error** in JSON metadata: Incorrect value for fileFormat. Expected: mp4, Found: MPEG-4.

with...

WARNING - **Incorrect** JSON metadata: Incorrect value for fileFormat. Expected: mp4, Found: MPEG-4.

**Comment by nkrabben** [comment]
Would it work to change all messages from "Error in blah blah" to "blah blah out of spec"?

**Comment by genfhk** [comment]
Yeah that works for me.
