### ISSUE TITLE
validate_bags.py - tool stops at first error encountered 

### ISSUE THREAD

**Issue by genfhk** [NYPL/ami-tools#56]
<img width="945" alt="Screen Shot 2021-08-18 at 10 31 22 AM" src="https://user-images.githubusercontent.com/18148763/129917049-9d4afe09-1122-4752-a39b-4f50447d6c68.png">

(in this case it stopped at 92%)

**Comment by nkrabben** [comment]
please check and close if addressed

**Comment by genfhk** [comment]
Closing this until it happens again
